version: "3.3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # map internal port 5432 to host port 6543
      - 6543:5432
    restart: always
    volumes:
      - ./pgtest-server-data-volume:/tmp

